#version: "3.3"
#version attribute is now obsolete 
services: 
  coldfusion: 
    container_name: cf2025_cfyaml
    image: adobecoldfusion/coldfusion:latest 
    ports: 
      - "8083:8500" 
    env_file: 
      - variables.env
    volumes: 
      - "./www:/app" 
    networks: 
      - webnet 
    #secrets: 
    #  - source: password 
    #    target: /opt/secrets/password

networks: 
  webnet: 
 
#secrets: 
#  password: 
#    external: true